# sentiment-analysis-using-naive-bayes

In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [16]:
df=pd.read_csv(r"C:\Users\divya\OneDrive\DS\EDA\archive50k\IMDB Dataset.csv")

In [17]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [18]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## Text Cleaning

1. Sample 10000 rows
2. Remove html tags
3. Remove special characters
4. Converting every thing to lower case
5. Removing Stop words
6. Stemming

In [19]:
df=df.sample(10000)

In [20]:
df.shape

(10000, 2)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 31601 to 46905
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [22]:
df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

C:\Users\divya\AppData\Local\Temp\ipykernel_31072\4240984564.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)
C:\Users\divya\AppData\Local\Temp\ipykernel_31072\4240984564.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'].replace({'positive':1,'negative':0},inplace=True)

In [23]:
df.head()

                                                  review  sentiment
31601  To be brief, the story is paper thin and you c...          1
34974  Do we really need any more narcissistic garbag...          0
33181  The show is really funny. Nice theme. Jokes an...          1
38514  I'm a pretty tolerable guy, when it comes to m...          0
11852  As an old white housewife I can still apprecia...          1

In [24]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[2].review)

'The show is really funny. Nice theme. Jokes and one liners are really good. With little extra tuning it can become a very popular show. But the only major negative point of this show is the cast. David Spade does a great job as Russell, Megyn Price does a good job. But who the hell did cast Patrick Warburton, Oliver Hudson and Bianca Kajlich.Technically Russell and Jeff are the main characters of the show, which make viewers wanna watch the show. Russell is a playboy and Jeff is a kind of frustrated family man, The relationship wiz... with an experience of all the problems a married couple face in a relationship.Patrick Warburton - does a horrible job as Jeff, he is not at all suited for the role. He is like a robot, literally there is no punch in his dialog delivery. Cast is really very important for viewers to like it. The bad acting certainly will take the show downhill...'

In [25]:
# Function to clean html tags
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [26]:
df['review']=df['review'].apply(clean_html)

In [27]:
# converting everything to lower

def convert_lower(text):
    return text.lower()

In [28]:
df['review']=df['review'].apply(convert_lower)

In [29]:
# function to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x

In [30]:
remove_special(' th%e @ classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare. forget pretty pictures painted for mainstream audiences, f')

' th e   classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary  it focuses mainly on emerald city  an experimental section of the prison where all the cells have glass fronts and face inwards  so privacy is not high on the agenda  em city is home to many  aryans  muslims  gangstas  latinos  christians  italians  irish and more    so scuffles  death stares  dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare  forget pretty pictures painted for mainstream audiences  f'

In [31]:
df['review']=df['review'].apply(remove_special)

In [32]:
# Remove the stop words
import nltk

In [38]:
from nltk.corpus import stopwords

In [43]:
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords

print(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\divya\AppData\Roaming\nltk_data...

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

[nltk_data]   Unzipping corpora\stopwords.zip.

In [44]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [45]:
df

                                                  review  sentiment
31601  to be brief  the story is paper thin and you c...          1
34974  do we really need any more narcissistic garbag...          0
33181  the show is really funny  nice theme  jokes an...          1
38514  i m a pretty tolerable guy  when it comes to m...          0
11852  as an old white housewife i can still apprecia...          1
...                                                  ...        ...
45058  nowhere near the original  it s quite accurate...          0
495     american nightmare  is officially tied  in my...          0
13406  there is so much bad to say about this movie a...          0
10089  this show is a perfect example of how the cbc ...          0
46905  this is the most ludicrous and laughable thril...          0

[10000 rows x 2 columns]

In [46]:

def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [ ]:
df['review']=df['review'].apply(remove_stopwords)

In [ ]:
df

In [25]:
# Perform stemming

from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [26]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [27]:
stem_words(['I','loved','loving','it'])

['I', 'love', 'love', 'it']

In [28]:
df['review']=df['review'].apply(stem_words)

In [29]:
df

                                                  review  sentiment
24181  [awhil, hook, show, like, ghost, hunter, desti...          0
33972  [man, gaston, modot, young, girl, lya, ly, go,...          0
36735  [complet, agre, review, watch, movi, 5, minut,...          0
7272   [take, make, use, familiar, plot, fine, perfor...          1
42497  [norwegian, film, start, man, jump, subway, ap...          1
...                                                  ...        ...
37487  [ok, american, humbl, scottish, opinion, steve...          0
7582   [movi, made, feel, miss, import, scene, begin,...          0
17748  [bewar, spoiler, movi, okay, goldi, hawn, chri...          1
24281  [rememb, aw, movi, bought, camelot, music, sto...          0
29109  [must, littl, skeptic, enter, cinema, watch, o...          1

[10000 rows x 2 columns]

In [30]:
# Join back

def join_back(list_input):
    return " ".join(list_input)

In [31]:
df['review']=df['review'].apply(join_back)

In [32]:
df['review']

24181    awhil hook show like ghost hunter destin truth...
33972    man gaston modot young girl lya ly go film con...
36735    complet agre review watch movi 5 minut look on...
7272     take make use familiar plot fine perform genui...
42497    norwegian film start man jump subway appar com...
                               ...
37487    ok american humbl scottish opinion steve marti...
7582     movi made feel miss import scene begin continu...
17748    bewar spoiler movi okay goldi hawn chri sarand...
24281    rememb aw movi bought camelot music store summ...
29109    must littl skeptic enter cinema watch oss117 f...
Name: review, Length: 10000, dtype: object

In [33]:
X=df.iloc[:,0:1].values

In [34]:
X.shape

(10000, 1)

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)

In [36]:
X=cv.fit_transform(df['review']).toarray()

In [37]:
X.shape

(10000, 2500)

In [38]:
X[0].mean()

0.1132

In [39]:
y=df.iloc[:,-1].values

In [40]:
y.shape

(10000,)

In [41]:
# X,y
# Training set
# Test Set(Already know the result)

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [43]:
X_train.shape

(8000, 2500)

In [44]:
X_test.shape

(2000, 2500)

In [45]:
y_train.shape

(8000,)

In [46]:
y_test.shape

(2000,)

In [47]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [48]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [49]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [50]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [51]:
y_test.shape

(2000,)

In [52]:
y_pred1.shape

(2000,)

In [53]:
from sklearn.metrics import accuracy_score

In [54]:
print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.7185
Multinomial 0.8295
Bernaulli 0.835